### PR TITLE
Remove .nix files

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
I just noticed that `default.nix` is in `.gitignore`, does this mean it should be removed for all subprojects, e.g. `gitlib-test` and `gitlib-hit`?

**Comment by jwiegley** [comment]
Yes, there shouldn't be an `.nix` files in this repository, since they are so easily generated.

**Comment by vaibhavsagar** [comment]
I've updated this PR accordingly.

**Comment by jwiegley** [comment]
Thank you!

**Comment by vaibhavsagar** [comment]
My pleasure :smile:

**Pull request merged**
