### PR TITLE
Add git blob rawsize to LibGit2 module

### PR DESCRIPTION
**Pull request by joshvera**

### CODE REVIEW

**Comment by joshvera** [comment]
Apologies wrong repo 😅

**Comment by jwiegley** [comment]
@joshvera I'm interested to know, which one is the right repo? :)

**Comment by joshvera** [comment]
@jwiegley I've got a fork going at https://github.com/joshvera/gitlib with a few minor changes. I'll open a few PRs here as soon as I have time. 😄

**Comment by jwiegley** [comment]
Thanks, that would be most welcome.  Last week I abandoned work on my `v4` branch to refocus my attention back on `master`, so I may have a few changes coming up myself.  I haven't started the work yet, though, so I'd be happy to bring your changes in before I start.

**Pull request closed without merging**
